type: array
description: |-
  Policy domain configurations.
  
x-akamai:
  file-path: schemas/all-config-open-output.yaml
items:
  type: object
  description: |
    Configurations.
  additionalProperties: false
  properties:
    configVersionId:
      type: integer
      description: |
        Unique identifier of the configuration version. Higher values are more recent versions.
    createdBy:
      type: string
      description: |
        Username of the person responsible for creating the configuration version.
    createdTimestamp:
      type: string
      description: |
        ISO 8601 timestamp indicating the creation time for the configuration version.
      format: date-time
    deployState:
      type: string
      description: |
        The configuration version's current deployment state. The `edited` state indicates that changes have been made but haven't been deployed. `deploying` indicates that the config is in the deployment process, while `deployed` indicates that all changes have been deployed.
      enum:
      - deployed
      - deploying
      - edited
    ipsAllocated:
      type: integer
      description: |
        Total number of virtual IP addresses allocated for the policy domain.
    ipsConfigured:
      type: integer
      description: |
        Total number of virtual IP addresses configured for the policy domain.
    pdSubnets:
      type: array
      description: |
        Subnets.
      items:
        type: object
        additionalProperties: false
        properties:
          configVersionId:
            type: integer
            description: |
              Unique identifier of the configuration version.
          legacyPdSubnet:
            type: boolean
            description: |
              Indicates whether Prolexic Proxy created the subnet.
          pdSubnet:
            type: string
            description: |
              Virtual IP address of the subnet.
          pdSubnetId:
            type: integer
            description: |
              Unique identifier of the subnet.
          vips:
            type: array
            description: |
              Virtual IP addresses.
            nullable: true
            items:
              type: object
              additionalProperties: false
              properties:
                type:
                  type: string
                  description: |
                    The type of IP address or subnet service configured.
                akamaiFrontend:
                  type: string
                  description: |
                    The Akamai virtual IP address that's been mapped to a back-end server or subnet.
                customerBackend:
                  type: string
                  description: |
                    IP address of a customer's server or subnet that's been mapped to a virtual IP address.
                legacyVip:
                  type: boolean
                  description: |
                    Indicates whether Prolexic Proxy created the virtual IP address.
                ports:
                  type: string
                  description: |
                    Comma-delimited string of virtual IP address ports open to Internet traffic.
                sourceIpProtocol:
                  type: string
                  description: |
                    Specifies the source IP for network packets received at a customer's back-end server or subnet. By default, packets are set to `NA`, identifying Akamai as the source IP. Other source IP options are `NAT46`, `CIP`, `PROXY_PROTOCOL_V1`, `PROXY_PROTOCOL_V2`, and `OPTION_28`. `NAT46` is only available if the virtual IP address has an IPv4 address and the back-end IP has an IPv6 address. The remaining options require the virtual IP address to be running on a TCP network.
                  enum:
                  - CIP
                  - PROXY_PROTOCOL_V1
                  - PROXY_PROTOCOL_V2
                  - OPTION_28
                  - NAT46
                  - NA
                vipId:
                  type: integer
                  description: |
                    Unique identifier of the virtual IP address.
    updatedBy:
      type: string
      description: |
        Username of the person for the most recent update of the configuration version.
      nullable: true
    updatedTimestamp:
      type: string
      description: |
        ISO 8601 timestamp indicating the time of the most recent update of the configuration version.
      format: date-time
