type: object
description: |
  Provides global settings details.
additionalProperties: false
required:
- blockRoamingTraffic
properties:
  globalSettingsId:
    type: integer
    description: |
      The unique ID for the global setting.
    readOnly: true
    minimum: 1
  blockRoamingTraffic:
    type: boolean
    description: |
      Blocks roaming traffic.
  quicklistMigrated:
    type: boolean
    description: |
      Migrates `quickList`.
  enableSourceIpBind:
    type: boolean
    description: |
      Enables the source IP binding.
  enableChinaRegion:
    type: boolean
    description: |
      Enables the China region for the deployment.
  asnExceptions:
    type: array
    description: |
      List of AS number exceptions.
    minItems: 0
    uniqueItems: true
    items:
      type: integer
      description: |
        AS number.
      minimum: 1
      maximum: 4294967294
