type: object
description: |
  V2 policy security settings.
additionalProperties: false
required:
- listId
- confirmedResponseId
- shouldNotifyConfirmed
- shouldNotifySuspected
properties:
  policyId:
    type: integer
    description: |
      Identifies the policy for the security setting.
    readOnly: true
    minimum: 1
  policyName:
    type: string
    description: |
      Name of the policy for the security setting.
    minLength: 1
  confirmedResponseId:
    type: integer
    description: |
      A unique identifier for the confirmed response.
    minimum: 1
  confirmedResponseInfo:
    type: object
    description: |
      Contains data about the confirmed response.
    additionalProperties: false
    required:
    - name
    - id
    properties:
      id:
        type: integer
        description: |
          A unique identifier for the confirmed response info.
        minimum: 1
      name:
        type: string
        description: |
          The name of the confirmed response info.
        minLength: 1
  listId:
    type: integer
    description: |
      A unique identifier for the list.
    minimum: 1
  listInfo:
    type: object
    description: |
      Contains data about the list.
    additionalProperties: false
    required:
    - name
    - id
    - categoryId
    properties:
      id:
        type: integer
        description: |
          A unique identifier for the list info.
        minimum: 1
      name:
        type: string
        description: |
          The name of the list info.
        minLength: 1
      categoryId:
        type: integer
        description: |
          The unique category ID.
        minimum: 1
      listType:
        type: string
        description: |
          The list type. See [List types](ref:list-types) for details on supported values.
        enum:
        - UNIFIED_BLOCK_LIST
        - UNIFIED_EXCEPTION_LIST
        - FQDN_LIST
        - AKAMAI
        - TOP_LEVEL_DOMAIN
        - WHITELIST
        - FILEHASHLIST
        - FILEHASH_BLOCK
        - DOMAIN_IP_LIST
        - URL_BLOCK
        - URL_BYPASS
  shouldNotifyConfirmed:
    type: boolean
    description: |
      Send alert on confirmed list hit.
  shouldNotifySuspected:
    type: boolean
    description: |
      Send alert on suspected list hit.
  suspectedResponseId:
    type: integer
    description: |
      A unique identifier for the suspected response.
    readOnly: true
    minimum: 1
  suspectedResponseInfo:
    type: object
    description: |
      Contains data about the suspected response.
    additionalProperties: false
    required:
    - name
    - id
    properties:
      id:
        type: integer
        description: |
          A unique identifier for the suspected response info.
        minimum: 1
      name:
        type: string
        description: |
          The name of the suspected response info.
        minLength: 1
  confirmedUsers:
    type: array
    description: |
      List of confirmed users.
    minItems: 0
    items:
      type: string
      minLength: 1
  confirmedGroups:
    type: array
    description: |
      List of confirmed groups.
    minItems: 0
    items:
      type: string
      minLength: 1
  suspectedUsers:
    type: array
    description: |
      List of suspected users.
    minItems: 0
    items:
      type: string
      minLength: 1
  suspectedGroups:
    type: array
    description: |
      List of suspected groups.
    minItems: 0
    items:
      type: string
      minLength: 1
  responseOverridesConfirmed:
    type: array
    description: |
      Lists of response overrides for confirmed response.
    minItems: 0
    items:
      $ref: response-override.yaml
  responseOverridesSuspected:
    type: array
    description: |
      Lists of response overrides for suspected response.
    minItems: 0
    items:
      $ref: response-override.yaml
