type: object
x-akamai:
  file-path: schemas/deployments.v6.yaml
additionalProperties: false
required:
- production
- staging
properties:
  production:
    type: object
    additionalProperties: false
    required:
    - multiStackedCertificates
    - networkConfiguration
    - primaryCertificate
    properties:
      multiStackedCertificates:
        type: array
        description: |
          Dual-stacked certificates include an ECDSA certificate in addition to an RSA certificate.
        items:
          type: object
          description: |
            Deployment may include many dual-stacked certificates.
          additionalProperties: false
          required:
          - certificate
          - trustChain
          properties:
            certificate:
              type: string
              description: |
                The certificate text.
              nullable: true
            expiry:
              type: string
              description: |
                The expiration date for the certificate.
            signatureAlgorithm:
              type: string
              description: |
                Identifies the SHA (Secure Hash Algorithm) function. The NSA (National Security Agency) designed this function to produce a hash of certificate contents, for use in a digital signature. This is either `SHA-1` for a 160-bit (20-byte) hash or `SHA-256` for a 256-bit (32-byte) hash. To ensure a secure hash function, use `SHA-256`.
              nullable: true
              enum:
              - SHA-1
              - SHA-256
            trustChain:
              type: string
              description: |
                The trust chain for the certificate.
              nullable: true
      networkConfiguration:
        type: object
        additionalProperties: false
        required:
        - quicEnabled
        - sniOnly
        properties:
          disallowedTlsVersions:
            type: array
            description: |
              Disallowed TLS protocols.
            items:
              type: string
          dnsNames:
            type: array
            description: |
              Names served by SNI-only enabled enrollments.
            items:
              type: string
          geography:
            type: string
            description: |
              Specifies the type of network where you want to deploy your certificate.  Use `core` to deploy across most of the world except for specially licensed areas.  Use `china+core` to include China, or `russia+core` to include Russia. Any non-`core` deployment needs to be enabled on your contract based on approval from the Chinese or Russian governments.
            enum:
            - core
            - china+core
            - russia+core
          mustHaveCiphers:
            type: string
            description: |
              Ciphers that you definitely want to include for your enrollment while deploying it on the network.
          ocspStapling:
            type: string
            description: |
              OCSP stapling setting for the deployment.
          preferredCiphers:
            type: string
            description: |
              Ciphers that you preferably want to include for your enrollment while deploying it on the network.
          quicEnabled:
            type: boolean
            description: |
              QUIC transport layer network protocol.
          secureNetwork:
            type: string
            description: |
              The type of deployment network. A value of `standard-tls` means Akamai's standard secure network, while `enhanced-tls` means Akamai's more secure network with PCI compliance capability.
          sniOnly:
            type: boolean
            description: |
              Server Name Indication (SNI) is an extension of the Transport Layer Security (TLS) networking protocol. It allows a server to present many certificates on the same IP address. All modern web browsers support the SNI extension. If you have the same SAN on two or more certificates with the SNI-only option set, Akamai may serve traffic using any certificate that matches the requested SNI hostname. You should avoid any certificates with overlapping SAN names when using SNI-only.
      ocspStapled:
        type: boolean
        description: |
          OCSP Stapling improves performance by including a valid OCSP response in every TLS handshake. You should enable this feature.
      ocspUris:
        type: array
        description: |
          URI used for OCSP stapling validation.
        nullable: true
        items:
          type: string
      primaryCertificate:
        type: object
        description: |
          Primary certificate of the enrollment.
        additionalProperties: false
        required:
        - certificate
        - trustChain
        nullable: true
        properties:
          certificate:
            type: string
            description: |
              The certificate text.
            nullable: true
          expiry:
            type: string
            description: |
              The expiration date for the certificate.
          signatureAlgorithm:
            type: string
            nullable: true
            enum:
            - SHA-1
            - SHA-256
          trustChain:
            type: string
            description: |
              The trust chain for the certificate.
            nullable: true
  staging:
    type: object
    additionalProperties: false
    required:
    - multiStackedCertificates
    - networkConfiguration
    - primaryCertificate
    properties:
      multiStackedCertificates:
        type: array
        description: |
          Dual-stacked certificates today include an ECDSA certificate in addition to an RSA certificate.
        items:
          type: object
          description: |
            Deployment may include many dual-stacked certificates.
          additionalProperties: false
          required:
          - certificate
          - trustChain
          properties:
            certificate:
              type: string
              description: |
                The certificate text.
              nullable: true
            expiry:
              type: string
              description: |
                The expiration date for the certificate.
            signatureAlgorithm:
              type: string
              description: |
                Identifies the SHA (Secure Hash Algorithm) function. The NSA (National Security Agency) designed this function to produce a hash of certificate contents, for use in a digital signature. This is either `SHA-1` for a 160-bit (20-byte) hash or `SHA-256` for a 256-bit (32-byte) hash. To ensure a secure hash function, use `SHA-256`.
              nullable: true
              enum:
              - SHA-1
              - SHA-256
            trustChain:
              type: string
              description: |
                The trust chain for the certificate.
              nullable: true
      networkConfiguration:
        type: object
        additionalProperties: false
        required:
        - quicEnabled
        - sniOnly
        properties:
          disallowedTlsVersions:
            type: array
            description: |
              Disallowed TLS protocols.
            items:
              type: string
          dnsNames:
            type: array
            description: |
              Names served by SNI-only enabled enrollments.
            items:
              type: string
          geography:
            type: string
            description: |
              Specifies the type of network where you want to deploy your certificate.  Use `core` to deploy across most of the world except for specially licensed areas.  Use `china+core` to include China, or `russia+core` to include Russia. Any non-`core` deployment needs to be enabled on your contract based on approval from the Chinese or Russian governments.
            enum:
            - core
            - china+core
            - russia+core
          mustHaveCiphers:
            type: string
            description: |
              Ciphers that you definitely want to include for your enrollment while deploying it on the network.
          ocspStapling:
            type: string
            description: |
              OCSP stapling setting for the deployment.
          preferredCiphers:
            type: string
            description: |
              Ciphers that you preferably want to include for your enrollment while deploying it on the network.
          quicEnabled:
            type: boolean
            description: |
              QUIC transport layer network protocol.
          secureNetwork:
            type: string
            description: |
              The type of deployment network. A value of `standard-tls` means Akamai's standard secure network, while `enhanced-tls` means Akamai's more secure network with PCI compliance capability.
          sniOnly:
            type: boolean
            description: |
              Server Name Indication (SNI) is an extension of the Transport Layer Security (TLS) networking protocol. It allows a server to present many certificates on the same IP address. All modern web browsers support the SNI extension. If you have the same SAN on two or more certificates with the SNI-only option set, Akamai may serve traffic using any certificate that matches the requested SNI hostname. You should avoid any certificates with overlapping SAN names when using SNI-only.
      ocspStapled:
        type: boolean
        description: |
          OCSP Stapling improves performance by including a valid OCSP response in every TLS handshake. We recommend all customers enable this feature.
      ocspUris:
        type: array
        description: |
          URI used for OCSP stapling validation.
        nullable: true
        items:
          type: string
      primaryCertificate:
        type: object
        description: |
          The primary certificate of the enrollment.
        additionalProperties: false
        required:
        - certificate
        - trustChain
        nullable: true
        properties:
          certificate:
            type: string
            description: |
              The certificate text.
            nullable: true
          expiry:
            type: string
            description: |
              The expiration date for the certificate.
          signatureAlgorithm:
            type: string
            nullable: true
            enum:
            - SHA-1
            - SHA-256
          trustChain:
            type: string
            description: |
              The trust chain for the certificate.
            nullable: true
